minecraft_version=1.21.1
loader_version=0.19.2
loom_version=1.16-SNAPSHOT
fabric_api_version=0.116.6+1.21.1
fabric_loader_min_version=0.19.2
midnightlib_version=1.9.1+1.21.1-fabric
java_version=21
rosetta_jar=C:/Users/natha/Documents/GitHub/Rosetta_Library/versions/1.21.1-fabric/build/libs/Rosetta-0.1.0-1.21.1-fabric.jar
